/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Bootloadable.h"
#include "Button.h"
#include "Button_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "SPI.h"
#include "SPI_SPI_UART.h"
#include "SPI_PINS.h"
#include "SPI_SPI_UART_PVT.h"
#include "SPI_PVT.h"
#include "SPI_BOOT.h"
#include "NRF_CE.h"
#include "NRF_CE_aliases.h"
#include "NRF_IRQ.h"
#include "NRF_IRQ_aliases.h"
#include "Clock.h"
#include "ExtInterrupt_Reg.h"
#include "Timer.h"
#include "ExtInterrupt_Reg_Interrupt.h"
#include "SysClock_ISR.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "SPI_SCBCLK.h"
#include "SPI_sclk_m.h"
#include "SPI_sclk_m_aliases.h"
#include "SPI_miso_m.h"
#include "SPI_miso_m_aliases.h"
#include "SPI_mosi_m.h"
#include "SPI_mosi_m_aliases.h"
#include "SPI_ss0_m.h"
#include "SPI_ss0_m_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

